# Generated by Django 5.0.6 on 2024-06-04 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_app', '0003_alter_sharedclass_uu_id'),
        ('social_app', '0002_alter_followers_email_alter_followers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_app.sharedclass'),
        ),
    ]
