# Generated by Django 5.0.6 on 2024-06-04 21:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_app', '0002_alter_sharedclass_uu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedclass',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('9630af8a-78bf-4004-b54a-9b6d1bd7996e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
